#!/usr/bin/env python3
"""Merge round-2 researcher feature inventories into the seed features.json,
then produce a self-contained HTML report (no fetch — opens via file://).
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).parent
SEED = HERE / "features.json"
HTML_IN = HERE / "feature-catalog.html"
HTML_OUT = HERE / "feature-catalog.html"  # rewrite in place

# Additional features culled from the 6 researcher syntheses, normalized.
# Curated for de-duplication against the seed and against each other.
NEW_FEATURES = [
    # --- AI-augment scan additions (employee) ---
    {"id":"voice-to-self-review","name":"Speak your self-review","description":"Dictate your reflection in your own language; system transcribes and lightly cleans up — keeps your voice, never rewrites.","primary_user":"employee","surface":"self-review","help_mode":"employee-makes-case","ai_mode":"translate","inspiration":["Leapsome Review Assistant","Spinach"],"complexity":"S","poc_fit":False,"trust_pattern":"Raw vs cleaned shown side by side; user picks which goes in."},
    {"id":"goal-language-coach","name":"SMART-goal language coach","description":"Suggests sharper phrasing on a goal as you write (SMART or COIN). Side-by-side; inline; never auto-replaces.","primary_user":"employee","surface":"goals","help_mode":"employee-makes-case","ai_mode":"translate","inspiration":["Mesh Maven","Lattice Writing Assistance"],"complexity":"S","poc_fit":False,"trust_pattern":"Original + suggestion shown; framework named ('SMART check')."},
    {"id":"claim-strengthener","name":"\"Add evidence?\" prompt","description":"When you write an unsupported claim ('I improved team velocity'), the system prompts: 'want to attach the PR, metric, or quote?' Never invents evidence.","primary_user":"employee","surface":"self-review","help_mode":"employee-makes-case","ai_mode":"retrieve","inspiration":["Macorva risk analysis","Lavender"],"complexity":"M","poc_fit":True,"trust_pattern":"Prompt is a question, not a rewrite. Dismissable."},
    {"id":"career-track-mirror","name":"\"Where does this map?\" reflector","description":"You describe an achievement; system shows which competency dimensions it touches in the framework — for self-positioning, not auto-rating.","primary_user":"employee","surface":"career-framework","help_mode":"employee-makes-case","ai_mode":"synthesize","inspiration":["Zavvy career frameworks"],"complexity":"M","poc_fit":False,"trust_pattern":"Shows exact framework text + 'possibly maps to' confidence."},
    {"id":"recognition-echo","name":"Recognition echo panel","description":"Sidebar surfacing structured recognition you received this cycle, ready to cite into your self-review with one click.","primary_user":"employee","surface":"self-review","help_mode":"employee-makes-case","ai_mode":"retrieve","inspiration":["Chorus snippet share","Workhuman"],"complexity":"S","poc_fit":True,"trust_pattern":"Only structured kudos. Visible only to the recipient until cited."},
    {"id":"evidence-autotag","name":"Evidence auto-tagging","description":"When you log an accomplishment, AI proposes goal + competency tags. You confirm or reject; never silent writes.","primary_user":"employee","surface":"evidence-layer","help_mode":"employee-makes-case","ai_mode":"synthesize","inspiration":["Linear Triage Intelligence"],"complexity":"M","poc_fit":False,"trust_pattern":"Top-3 candidates + 'none of these'. Reject is first-class."},
    {"id":"evidence-search","name":"Self-evidence search","description":"Inside the self-review draft, search 'show me everything I logged about onboarding.' Returns your own HRIS entries as citable snippets.","primary_user":"employee","surface":"evidence-layer","help_mode":"employee-makes-case","ai_mode":"retrieve","inspiration":["Glean personal scope"],"complexity":"M","poc_fit":False,"trust_pattern":"Strictly your own data. Search history not shared with manager."},
    {"id":"career-recall","name":"Career-conversation recall","description":"Ask 'what did my manager say about my presentation skills last year?' — semantic search across your own past 1:1s, reviews, check-ins.","primary_user":"employee","surface":"career-framework","help_mode":"employee-makes-case","ai_mode":"retrieve","inspiration":["Mem AI"],"complexity":"S","poc_fit":False,"trust_pattern":"Only items the user can already read. Searches private."},
    {"id":"personal-streak","name":"Private growth streak","description":"Private counter of self-development behaviors (check-ins logged, feedback requested, learning hours). Visible only to you.","primary_user":"employee","surface":"cross-cutting","help_mode":"employee-makes-case","ai_mode":"none","inspiration":["Lavender leaderboard inverted"],"complexity":"S","poc_fit":False,"trust_pattern":"Private by architecture. No share button, no manager view."},
    {"id":"self-tone-preview","name":"Self-review tone preview","description":"Live linting of hedging language, passive voice, weak verbs, and 'I' vs 'we' balance on your draft. Ephemeral; never stored.","primary_user":"employee","surface":"self-review","help_mode":"employee-makes-case","ai_mode":"synthesize","inspiration":["Lavender"],"complexity":"S","poc_fit":True,"trust_pattern":"Same model as a spellchecker. Never visible to manager."},
    {"id":"review-checklist","name":"Cycle micro-checklist","description":"Visual time-boxed checklist: gather goals → list wins → request peer feedback → draft → tone-preview → submit. Draggable, slot-aware, never auto-books.","primary_user":"employee","surface":"cycle-admin","help_mode":"employee-makes-case","ai_mode":"none","inspiration":["Motion task planning"],"complexity":"S","poc_fit":True,"trust_pattern":"Visual scheduler only. Nothing lands on the real calendar without explicit click."},
    {"id":"review-writing-block","name":"Review-writing time blocks (proposed)","description":"During cycle window, propose 60–90 min calendar holds for review writing. Employee and manager get their own proposals; explicit accept required.","primary_user":"employee","surface":"cycle-admin","help_mode":"employee-makes-case","ai_mode":"none","inspiration":["Reclaim Focus Time"],"complexity":"M","poc_fit":False,"trust_pattern":"Proposed only. Easy to decline; no nag."},
    {"id":"shipped-this-half","name":"\"Shipped this half\" draft","description":"At cycle close, auto-draft an accomplishments section from your HRIS-only structured data (closed goals, OKR check-ins, recognition, projects).","primary_user":"employee","surface":"self-review","help_mode":"employee-makes-case","ai_mode":"draft","inspiration":["Linear cycle summary"],"complexity":"M","poc_fit":True,"trust_pattern":"Always presented as 'draft — edit before submit'. Source rows visible inline."},

    # --- AI-augment additions (manager) ---
    {"id":"1on1-prep-card","name":"1:1 prep card","description":"Before each 1:1, a read-only digest of the report's recent goals, progress they self-logged, recognition received, your last 3 notes, next career milestone.","primary_user":"manager","surface":"1on1","help_mode":"manager-does-job","ai_mode":"retrieve","inspiration":["Salesloft Coach","Mesh Maven","Glean"],"complexity":"S","poc_fit":True,"trust_pattern":"Pure retrieval. Nothing new generated. Manager adds notes during the meeting."},
    {"id":"unresolved-thread-digest","name":"Unresolved-thread digest","description":"Pre-1:1 panel of items you opened but never closed: goals with no progress in 14 days, action items you wrote without a checkbox, feedback you gave last cycle with no revisit.","primary_user":"manager","surface":"1on1","help_mode":"manager-does-job","ai_mode":"retrieve","inspiration":["Gong moments"],"complexity":"M","poc_fit":True,"trust_pattern":"Only operates on the manager's own notes. No cross-manager comparison."},
    {"id":"1on1-typed-notepad","name":"1:1 typed notepad with action routing","description":"Typed (never recorded) 1:1 notes. Mark a line 'action: report' or 'action: me' and it auto-routes to the right place.","primary_user":"manager","surface":"1on1","help_mode":"manager-does-job","ai_mode":"synthesize","inspiration":["Spinach typed mode"],"complexity":"S","poc_fit":True,"trust_pattern":"Never records audio. Report sees only the 'share' lines."},
    {"id":"conversation-starters","name":"Conversation-starter library","description":"Tagged playbook of opening frames for hard 1:1 topics: underperformer who is unaware, high-performer who is bored, promotion deferred, first feedback after a miss.","primary_user":"manager","surface":"1on1","help_mode":"manager-does-job","ai_mode":"retrieve","inspiration":["Gong call-moment library"],"complexity":"S","poc_fit":True,"trust_pattern":"Static content authored by HR. LLM only rewrites the template, never the personal data."},
    {"id":"conversation-sandbox","name":"Hard-conversation sandbox","description":"Ephemeral role-play partner. Type the situation (no employee name) and rehearse a hard 1:1 with a Socratic AI. No storage, no logs.","primary_user":"manager","surface":"1on1","help_mode":"manager-does-job","ai_mode":"draft","inspiration":["Bravely (inverted)"],"complexity":"M","poc_fit":False,"trust_pattern":"No employee identifiers accepted. Transcripts ephemeral. Aggregate topic stats only."},
    {"id":"feedback-tone-check","name":"Feedback tone check (manager)","description":"Pre-submit linter on manager-written feedback: flags gendered/biased phrasing, vagueness, missing forward-action.","primary_user":"manager","surface":"manager-review","help_mode":"manager-does-job","ai_mode":"synthesize","inspiration":["Lavender","Workhuman DEI Coach","Macorva bias check"],"complexity":"S","poc_fit":True,"trust_pattern":"Suggestions only. Manager sees lint privately; HR never sees flagged items."},
    {"id":"draft-shaper-not-drafter","name":"Review structure scaffolder","description":"Not a draft. A checklist: 'Strengths section is empty', 'You mentioned 3 examples, all Q4 — gap in H1?'. Helps you not miss sections.","primary_user":"manager","surface":"manager-review","help_mode":"manager-does-job","ai_mode":"synthesize","inspiration":["Macorva risk analysis"],"complexity":"S","poc_fit":True,"trust_pattern":"Gaps are questions, not autofills."},
    {"id":"grounded-rationale","name":"Grounded rationale draft","description":"For a proposed rating, system drafts a rationale paragraph citing only the evidence the manager has already attached. Refuses to invent.","primary_user":"manager","surface":"manager-review","help_mode":"manager-does-job","ai_mode":"draft","inspiration":["Notion AI grounded generation"],"complexity":"M","poc_fit":True,"trust_pattern":"Will not generate unsupported claims. If evidence is missing, returns a checklist."},
    {"id":"calibration-voice-reference","name":"Calibration-voice reference panel","description":"Side panel showing typical phrasing per rating band — so managers self-calibrate during drafting without forced wording.","primary_user":"manager","surface":"manager-review","help_mode":"manager-does-job","ai_mode":"retrieve","inspiration":["Grammarly brand-tone profile"],"complexity":"M","poc_fit":False,"trust_pattern":"Never auto-changes wording. Reference only. Corpus owned by calibration committee, refreshed each cycle."},
    {"id":"post-review-coaching-prompts","name":"Post-submit coaching prompts","description":"After submitting a review, the system asks the manager Socratic questions: 'What's one specific behavior change you want to see by next cycle? What support will you provide?'","primary_user":"manager","surface":"manager-review","help_mode":"manager-does-job","ai_mode":"draft","inspiration":["Mesh Maven","Bunch.ai"],"complexity":"S","poc_fit":True,"trust_pattern":"Questions only. Output is the manager's plan, not AI's."},
    {"id":"calibration-prep-pack","name":"Calibration evidence pack","description":"Per-report evidence pack for calibration: quotes from feedback, goal completion, scope of work. Calibrators discuss; AI does not propose levels.","primary_user":"manager","surface":"calibration","help_mode":"manager-does-job","ai_mode":"retrieve","inspiration":["Lattice Performance Insights minus the recommender"],"complexity":"M","poc_fit":True,"trust_pattern":"Evidence only; explicit 'no recommendation' disclaimer."},
    {"id":"question-bank-1on1","name":"Situational 1:1 question suggester","description":"Given current context (just shipped X, OKR Y in red, recent peer feedback Z), suggest 3 1:1 questions. Manager picks 0 or more.","primary_user":"manager","surface":"1on1","help_mode":"manager-does-job","ai_mode":"synthesize","inspiration":["Bunch.ai"],"complexity":"S","poc_fit":False,"trust_pattern":"Openers, not scripts. Named 'suggestions'."},

    # --- AI-augment additions (peer) ---
    {"id":"peer-specificity-coach","name":"Specificity coach for peers","description":"When a peer writes 'great team player,' the system prompts: 'Can you point to a specific moment?' Escapable — never blocks submission.","primary_user":"peer","surface":"peer-feedback","help_mode":"peer-contributes","ai_mode":"synthesize","inspiration":["Effy AI follow-up prompts"],"complexity":"S","poc_fit":True,"trust_pattern":"Prompt is escapable ('submit anyway')."},
    {"id":"peer-feedback-translation","name":"Peer feedback language bridge","description":"Peer writes feedback in their native language; subject reads it in theirs. Both versions saved; original marked canonical.","primary_user":"peer","surface":"peer-feedback","help_mode":"peer-contributes","ai_mode":"translate","inspiration":["Spinach multilingual"],"complexity":"S","poc_fit":True,"trust_pattern":"Both versions visible to the subject."},
    {"id":"peer-tone-softener","name":"Optional tone softener","description":"For critical feedback, an opt-in 'want a more constructive phrasing?' suggestion — without watering down content.","primary_user":"peer","surface":"peer-feedback","help_mode":"peer-contributes","ai_mode":"translate","inspiration":["Workhuman DEI Coach"],"complexity":"S","poc_fit":True,"trust_pattern":"Opt-in only. Original and softened shown side by side."},
    {"id":"peer-feedback-from-collab","name":"\"Help me write feedback for X\" assembler","description":"When you click 'give feedback to X,' the system surfaces shared work artifacts you both touched — so you write from collaboration, not blank page.","primary_user":"peer","surface":"peer-feedback","help_mode":"peer-contributes","ai_mode":"retrieve","inspiration":["Glean","Leapsome AI Copilot"],"complexity":"L","poc_fit":False,"trust_pattern":"Collabs are links, not summaries. Peer writes the prose."},
    {"id":"recognition-specificity","name":"Recognition specificity coach","description":"When someone writes 'great job!', the system asks 'great job at what specifically?' before sending. Doesn't replace; sharpens.","primary_user":"peer","surface":"peer-feedback","help_mode":"peer-contributes","ai_mode":"synthesize","inspiration":["Workhuman Recognition Advisor"],"complexity":"S","poc_fit":True,"trust_pattern":"Send-anyway escape hatch. Framed as suggestion, not block."},
    {"id":"recognition-nudge","name":"\"Have you considered recognizing X?\" nudge","description":"Surfaces low-recognition moments (a colleague shipped something nobody acknowledged) as a *suggestion*, not auto-recognition.","primary_user":"peer","surface":"peer-feedback","help_mode":"peer-contributes","ai_mode":"synthesize","inspiration":["Workhuman (avoiding auto-recognition anti-pattern)"],"complexity":"M","poc_fit":False,"trust_pattern":"Nudge is one-click dismissable. Never sends without explicit write."},

    # --- AI-augment additions (HR) ---
    {"id":"survey-theme-clusterer","name":"Survey theme clusterer","description":"HR loads engagement-survey free-text responses; system clusters into themes with example quotes. Themes labeled by AI but HR can rename/merge/split.","primary_user":"hr","surface":"cycle-insights","help_mode":"hr-sees-patterns","ai_mode":"synthesize","inspiration":["Lattice Engagement Insights"],"complexity":"M","poc_fit":True,"trust_pattern":"Each theme expands to show every supporting quote. HR can dispute or rename."},
    {"id":"unanswered-question-log","name":"\"What employees keep asking\" log","description":"Dashboard of questions the policy-Q&A bot couldn't answer — gap-finder for the employee handbook.","primary_user":"hr","surface":"cycle-insights","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Glean scouts"],"complexity":"S","poc_fit":True,"trust_pattern":"Aggregated counts, anonymized. HR decides what to write."},
    {"id":"cycle-completion-nag","name":"Personalized completion nudge","description":"Instead of broadcast emails, the system generates contextual nudges: 'You have 3 reviews due — here's the suggested order, longest collaboration first.'","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"synthesize","inspiration":["Effy status tracking"],"complexity":"S","poc_fit":True,"trust_pattern":"Suggestion can be ignored. Never marks complete on behalf."},
    {"id":"process-health-monitor","name":"Cycle process-health monitor","description":"Surfaces patterns: which managers submit reviews 2× faster than average, which 360 raters always say 'exceeds,' calibration meetings that ended in <30 min. Pattern surface, not action.","primary_user":"hr","surface":"cycle-insights","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["PerformYard analytics"],"complexity":"M","poc_fit":True,"trust_pattern":"Patterns are conversation starters, not auto-tickets."},
    {"id":"comp-rationale-explainer","name":"Compensation rationale explainer","description":"After humans decide comp, the system writes a personalized explanation pulling from the actual factors (band, position-in-range, performance signals). Does NOT propose the number.","primary_user":"hr","surface":"comp-letter","help_mode":"hr-sees-patterns","ai_mode":"draft","inspiration":["PerformYard comp clarity"],"complexity":"M","poc_fit":True,"trust_pattern":"Explanation cites policy components. Manager reviews before send. Employee follow-ups route to the manager."},
    {"id":"cycle-initiative","name":"Cycle initiative dashboard","description":"Opt-in org-level behavioral nudge during a cycle ('every manager spends ≥30 min in dedicated review writing per report'). Measured at team level, never individual.","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Reclaim Initiatives"],"complexity":"M","poc_fit":False,"trust_pattern":"Team-level only. Easy team opt-out. Initiative ends with cycle."},

    # --- Career framework additions ---
    {"id":"framework-browse","name":"Browse the framework in-product","description":"Skill matrix as a navigable graph: levels × dimensions × paths. Click a level, see all competencies × expectations. PDFs go away.","primary_user":"employee","surface":"career-framework","help_mode":"employee-makes-case","ai_mode":"retrieve","inspiration":["Progression.fyi","Lattice Grow","GitLab handbook"],"complexity":"M","poc_fit":False,"trust_pattern":"Framework is structured data — searchable, linkable, versioned."},
    {"id":"radar-profile","name":"Per-employee radar profile","description":"Radar chart of your assessed level per competency (not one global level). Snowflake-shape is native, not derived.","primary_user":"employee","surface":"career-framework","help_mode":"employee-makes-case","ai_mode":"retrieve","inspiration":["engineeringladders.com","Notion templates"],"complexity":"S","poc_fit":False,"trust_pattern":"Each dimension cites the evidence behind the assessment."},
    {"id":"competency-heatmap","name":"Team competency heatmap","description":"Team-level heatmap of strengths and gaps across competencies. Helps managers spot 'we're thin on system design at L4.'","primary_user":"manager","surface":"career-framework","help_mode":"manager-does-job","ai_mode":"aggregate","inspiration":["Lattice Grow team view"],"complexity":"M","poc_fit":False,"trust_pattern":"Team-level only. Never compares individuals against each other."},
    {"id":"framework-versioning","name":"Framework versioning + diff","description":"Diff a framework version against the previous one. Tell employees exactly what changed and why.","primary_user":"hr","surface":"career-framework","help_mode":"hr-sees-patterns","ai_mode":"retrieve","inspiration":["GitLab handbook working-group"],"complexity":"M","poc_fit":False,"trust_pattern":"Changelog is public. Old versions remain queryable for ongoing review cycles."},
    {"id":"anchor-search","name":"Anchor-behavior search","description":"Search 'who has demonstrated anchor behavior X?' across submitted evidence. Helpful for talent reviews and succession.","primary_user":"hr","surface":"career-framework","help_mode":"hr-sees-patterns","ai_mode":"retrieve","inspiration":["Anchor behaviors as arrays on LevelExpectation"],"complexity":"M","poc_fit":False,"trust_pattern":"Returns evidence, not labels. HR draws the conclusion."},
    {"id":"track-switch-wizard","name":"IC ↔ Manager track-switch wizard","description":"Show level equivalence when moving IC→Manager or Backend→Platform — Square's L6=L6 pattern.","primary_user":"employee","surface":"career-framework","help_mode":"employee-makes-case","ai_mode":"retrieve","inspiration":["Square/Block Growth Framework","GitLab"],"complexity":"M","poc_fit":False,"trust_pattern":"Exploratory; nothing committed until the employee initiates a mobility conversation."},
    {"id":"salary-band-reveal","name":"My salary band reveal","description":"Buffer-style transparency: see the band for your current level + location, and the band for the next level if you promote. Mid-band + percentile visible.","primary_user":"employee","surface":"pay-transparency","help_mode":"employee-makes-case","ai_mode":"retrieve","inspiration":["Buffer salary","Ravio employee view"],"complexity":"S","poc_fit":False,"trust_pattern":"Band is the source of truth. No surprise ranges."},

    # --- Compliance additions (EUPT/AI Act/GDPR/8-country) ---
    {"id":"per-decision-rationale","name":"Per-decision rationale capture","description":"Every comp decision (offer, raise, promotion, bonus, equity) requires structured rationale tied to gender-neutral criteria (skills, effort, responsibility, working conditions). Frozen at decision time — legal evidence for burden-of-proof reversal.","primary_user":"manager","surface":"compliance","help_mode":"manager-does-job","ai_mode":"draft","inspiration":["EU PT 2023/970 burden-of-proof reversal"],"complexity":"M","poc_fit":True,"trust_pattern":"Immutable once decision lands. Reason field is required for high-stakes changes."},
    {"id":"right-to-info-request","name":"EU PT right-to-information request","description":"Employee self-service flow: request own pay info + comparator-group medians by sex. 2-month SLA, audit log, annual auto-reminder.","primary_user":"employee","surface":"compliance","help_mode":"employee-makes-case","ai_mode":"none","inspiration":["EU PT Article 7"],"complexity":"M","poc_fit":False,"trust_pattern":"Request logged with timestamps. Response SLA visible. HR sees the queue."},
    {"id":"eu-pt-gap-report","name":"EUPT gender pay-gap report","description":"Median + mean pay gap, total + by variable/equity component, broken down by category of workers doing equal/equivalent work. Annual for ≥250.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["EU PT Article 9"],"complexity":"L","poc_fit":False,"trust_pattern":"Methodology documented in-product. Numbers tie to live population at export time."},
    {"id":"joint-pay-assessment","name":"Joint pay assessment workflow","description":"When unexplained gap ≥5% in any category isn't remedied in 6 months, trigger a joint assessment with worker reps (CSE / Betriebsrat / RSU / OR / Plan de Igualdad).","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["EU PT Article 10"],"complexity":"L","poc_fit":False,"trust_pattern":"Worker-rep export pack auto-generated. Status tracking across the 6-month remediation window."},
    {"id":"band-in-job-posting","name":"Band-in-job-posting integration","description":"Push salary range into ATS/job postings; block postings without a band; ban salary-history field in candidate forms.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["EU PT Article 5","Trusaic"],"complexity":"S","poc_fit":False,"trust_pattern":"ATS integration is the enforcement point. Block is hard, not soft."},
    {"id":"annual-right-to-info-reminder","name":"Annual right-to-info reminder","description":"Auto-notifies each employee yearly of their EU PT right to request pay information. Required by directive.","primary_user":"employee","surface":"compliance","help_mode":"employee-makes-case","ai_mode":"none","inspiration":["EU PT Article 7(4)"],"complexity":"S","poc_fit":False,"trust_pattern":"Once-per-year, opt-out audited."},
    {"id":"fr-index-egalite","name":"Index Égalité Femmes-Hommes (FR)","description":"Auto-computed 100-point Penicaud score on 5 indicators; publication-ready by 1 March each year.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Code du travail L1142-9","Lucca Pagga"],"complexity":"M","poc_fit":False,"trust_pattern":"Official methodology cited. Score visible to leadership; not to managers in-cycle."},
    {"id":"fr-nao-evidence","name":"NAO / CSE evidence pack (FR)","description":"Generate comp aggregates by category × gender for the Négociation Annuelle Obligatoire and CSE consultation; track negotiation conclusions.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["L2242-1"],"complexity":"M","poc_fit":False,"trust_pattern":"Export pack signed by HRBP. Conclusions logged in BDESE."},
    {"id":"fr-entretien-professionnel","name":"Entretien professionnel scheduler (FR)","description":"Track the every-2-year (or post-2025 every-4-year) career-development interview obligation per employee under L6315-1. Flag overdue.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Code du travail L6315-1"],"complexity":"S","poc_fit":False,"trust_pattern":"Distinct from Progress Review. Required by FR labor law regardless of perf cycle."},
    {"id":"de-betriebsvereinbarung","name":"Betriebsvereinbarung config layer (DE)","description":"Every monitoring/evaluation parameter (data collected, who sees it, retention, AI use) configurable per-deployment, exportable as draft works agreement.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"draft","inspiration":["BetrVG §87(1) No. 6"],"complexity":"L","poc_fit":False,"trust_pattern":"Required by DE law (broad interpretation — even Excel triggers §87). Audit trail per config change."},
    {"id":"de-entgelttransparenz","name":"Entgelttransparenzgesetz comparator response (DE)","description":"Automated comparator-group median computation for individual pay-info requests (≥6 comparators, opposite-sex, equivalent role).","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Entgelttransparenzgesetz 2017"],"complexity":"M","poc_fit":False,"trust_pattern":"Request and response both logged. Employee receives signed response."},
    {"id":"it-rapporto-biennale","name":"Rapporto biennale generator (IT)","description":"Ministry-of-Labour portal-format export of biennial gender report. UNI/PdR 125 certification-ready data.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Law 162/2021, Art. 46"],"complexity":"M","poc_fit":False,"trust_pattern":"Schema matches MITE portal. Submission-ready."},
    {"id":"it-livello-aware","name":"CCNL livello attribute (IT)","description":"First-class CCNL classification level on every employee + every comp decision. Decompose total comp into CCNL-mandated vs employer-discretionary.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Italian CCNL system"],"complexity":"M","poc_fit":False,"trust_pattern":"CCNL bands are the floor. Discretionary comp is the variable."},
    {"id":"es-registro-retributivo","name":"Registro retributivo export (ES)","description":"Pay register in RD 902/2020 schema: average + median by sex × category × level, including all supplements.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["RD 902/2020"],"complexity":"M","poc_fit":False,"trust_pattern":"Annual update. Auditable computation chain."},
    {"id":"es-auditoria-retributiva","name":"Auditoría retributiva workflow (ES)","description":"Pay-audit workflow producing the Plan de Igualdad diagnostic. Justification capture for any gap above threshold.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"draft","inspiration":["RD 902/2020 Art. 7-8"],"complexity":"M","poc_fit":False,"trust_pattern":"Diagnostic frozen at audit time. Worker-rep export ready."},
    {"id":"be-biennial-analysis","name":"Belgian biennial comparative analysis (BE)","description":"Long-form pay-structure analysis (function × seniority × qualifications × gender) per Loi 22 April 2012.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Loi 22 April 2012"],"complexity":"M","poc_fit":False,"trust_pattern":"Federal-format export."},
    {"id":"nl-methodology-approval","name":"Works-council methodology approval (NL)","description":"Per the Dutch EU PT draft, the works council approves the *methodology* (not the data). Configurable methodology object with approval workflow.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["WOR + Dutch EUPTD draft"],"complexity":"M","poc_fit":False,"trust_pattern":"Methodology versioned. Approval is per-version."},
    {"id":"pt-act-gender-gap","name":"ACT gender pay-gap report (PT)","description":"Law 60/2018 format report + remediation-plan tracker with ACT (Autoridade para as Condições do Trabalho) submission status.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Law 60/2018"],"complexity":"M","poc_fit":False,"trust_pattern":"Submission audit chain. Remediation plan tracked in-product."},
    {"id":"at-einkommensbericht","name":"Einkommensbericht export (AT)","description":"Biennial income report by collective-agreement category × gender (mean + median). Secure Betriebsrat-only delivery channel.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Gleichbehandlungsgesetz §11a"],"complexity":"S","poc_fit":False,"trust_pattern":"Confidential — only Betriebsrat + employees may see."},
    {"id":"ai-act-fria","name":"AI Act FRIA template & log","description":"Auto-populate Fundamental Rights Impact Assessment from system configuration. Refresh on scope change. Deadline 2 Aug 2026.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"draft","inspiration":["EU AI Act Article 27"],"complexity":"L","poc_fit":False,"trust_pattern":"Pre-filled from system metadata. DPO + HRBP sign-off."},
    {"id":"ai-act-human-in-loop","name":"AI Act human-in-loop enforcement","description":"Block any 'significant-effect' decision (promo, termination, comp >X%) from being finalized without recorded meaningful human review with override capability.","primary_user":"manager","surface":"compliance","help_mode":"manager-does-job","ai_mode":"none","inspiration":["EU AI Act Article 14","GDPR Article 22"],"complexity":"M","poc_fit":False,"trust_pattern":"Human review checkpoint logged. Override is first-class."},
    {"id":"ai-act-right-to-explanation","name":"AI Act right-to-explanation","description":"Per-decision explanation generator for any AI-influenced output. Employee-facing contestation flow.","primary_user":"employee","surface":"compliance","help_mode":"employee-makes-case","ai_mode":"draft","inspiration":["EU AI Act Article 86"],"complexity":"M","poc_fit":False,"trust_pattern":"Explanation cites the AI artifacts that touched the decision. Contestation routes to HRBP + DPO."},
    {"id":"ai-act-deployment-notification","name":"Worker-rep AI deployment notification","description":"Pre-deployment notification workflow to CSE / Betriebsrat / RSU / OR / Plan de Igualdad commission before any high-risk AI feature is enabled.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["EU AI Act Article 26(7)"],"complexity":"S","poc_fit":False,"trust_pattern":"Notification record is immutable. Activation gated on receipt confirmation."},
    {"id":"dsar-export","name":"DSAR export for perf records","description":"Machine-readable export of all perf data per employee — records, manager notes, peer verbatims, AI outputs and their explanations. 1-month SLA.","primary_user":"employee","surface":"compliance","help_mode":"employee-makes-case","ai_mode":"none","inspiration":["GDPR Article 15"],"complexity":"M","poc_fit":False,"trust_pattern":"Subject-owned export. DPO oversight. Includes AI artifacts that touched the file."},
    {"id":"retention-policy-engine","name":"Country-aware retention engine","description":"Per-record retention with country defaults (FR 2y post-departure CNIL guidance; DE 6-10y payroll; etc.). Auto-purge with litigation hold flag.","primary_user":"hr","surface":"compliance","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["GDPR Art. 5(1)(e)","CNIL HR guidance"],"complexity":"M","poc_fit":False,"trust_pattern":"Retention policy versioned per country. Hold-on-litigation overrides default."},

    # --- OSS / data-model additions ---
    {"id":"template-per-role","name":"Appraisal template per role","description":"Reusable template (KRAs + criteria + weights) attached to a role/designation. Same template applies across multiple cycles.","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Frappe HRMS Appraisal Template"],"complexity":"M","poc_fit":True,"trust_pattern":"Templates versioned. Changes don't retroactively alter past cycles."},
    {"id":"kra-atomic","name":"KRA dimension (atomic)","description":"Atomic Key Responsibility Area definition (title + description). Reused across templates and goals.","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Frappe HRMS KRA"],"complexity":"S","poc_fit":True,"trust_pattern":"Single source of truth for KRA names. Versioned."},
    {"id":"criteria-atomic","name":"Rating criterion (atomic)","description":"Atomic feedback criterion ('Communication', 'Ownership'). Reused across templates, self-ratings and feedback records.","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Frappe HRMS Employee Feedback Criteria"],"complexity":"S","poc_fit":True,"trust_pattern":"One table, three contexts — the polymorphic-rating-row pattern."},
    {"id":"polymorphic-rating-row","name":"Polymorphic rating row","description":"One row shape (criteria + weight + rating value) reused as template (no value), self-ratings, and peer/manager ratings. Frappe's one-table-three-uses pattern.","primary_user":"hr","surface":"cross-cutting","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Frappe HRMS"],"complexity":"M","poc_fit":True,"trust_pattern":"Schema enforces consistency. Calibration committee owns the criteria + weights."},
    {"id":"kra-auto-aggregation","name":"KRA auto-score from goal progress","description":"KRA score on the appraisal is auto-computed from the progress of goals tagged with that KRA (weighted average).","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Frappe Appraisal KRA"],"complexity":"M","poc_fit":True,"trust_pattern":"Deterministic; no judgment. Bridge between 'employee owns goals' and 'manager rates KRAs.'"},
    {"id":"manual-vs-auto-toggle","name":"Goal-rating mode toggle","description":"Per-cycle switch between auto-score-from-goal-progress and manager-rates-each-goal-manually.","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Frappe rate_goals_manually"],"complexity":"S","poc_fit":True,"trust_pattern":"Cycle-level decision. Documented in cycle metadata."},
    {"id":"180-360-mode","name":"180° / 360° mode","description":"Configurable: 180° = self + manager + reports; 360° = + peers. Cycle-level setting.","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["evalytics"],"complexity":"S","poc_fit":True,"trust_pattern":"Mode visible to participants. Settings frozen at cycle launch."},
    {"id":"reviewer-relationship","name":"Reviewer relationship tagging","description":"Tag each feedback record as self / manager / direct_report / peer / skip-level. Drives visibility and weighting.","primary_user":"hr","surface":"peer-feedback","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["evalytics","Lattice convention"],"complexity":"S","poc_fit":True,"trust_pattern":"Relationship derived from org chart at request time; frozen on submission."},
    {"id":"merit-matrix-2d","name":"Merit-increase matrix (2D grid)","description":"Editable grid (perf-quartile × compa-ratio-quartile) → merit %. People team edits once; system applies per Qontoer.","primary_user":"hr","surface":"comp-planning","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["LiviaMoreira/merit-increase-matrix"],"complexity":"M","poc_fit":True,"trust_pattern":"Matrix is visible to managers. Overrides are visible to HRBP."},
    {"id":"merit-eligibility-gates","name":"Merit eligibility gates","description":"Boolean gate set (12+ mo tenure, perf ≥ 3, not on PIP, no recent promo) — Qontoers must pass all gates to enter the merit pool.","primary_user":"hr","surface":"comp-planning","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Cadence_HR_HUB 6-gate engine"],"complexity":"M","poc_fit":True,"trust_pattern":"Gates configured by People team. Exceptions require HRBP sign-off."},
    {"id":"budget-aware-allocation","name":"Budget-aware raise allocation","description":"Given a raise budget + per-employee fair-target deltas, allocate raises minimizing % pay-deficit vs market. Optimization, not a matrix.","primary_user":"hr","surface":"comp-planning","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["robjailall/raise-calculator"],"complexity":"L","poc_fit":False,"trust_pattern":"Optimization objective visible. Manager can override and the system tracks deviation from optimum."},
    {"id":"final-score-aggregation","name":"Final score aggregation","description":"Read-only aggregate of goal + self + feedback weighted per cycle config. The Frappe `final_score_formula` pattern.","primary_user":"hr","surface":"cycle-admin","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Frappe HRMS"],"complexity":"S","poc_fit":True,"trust_pattern":"Formula visible to everyone. Manager sees the components, not just the aggregate."},
    {"id":"compa-ratio-traffic-light","name":"Compa-ratio bucket labels","description":"Color-coded buckets: Critical Under (<0.85) / Below (0.85–0.95) / Aligned (0.95–1.05) / Above (1.05–1.15) / Over (>1.15).","primary_user":"manager","surface":"comp-planning","help_mode":"manager-does-job","ai_mode":"aggregate","inspiration":["Pay-Equity-Analyzer"],"complexity":"S","poc_fit":True,"trust_pattern":"Buckets are aids; manager always sees the raw compa-ratio."},

    # --- Calibration UX additions ---
    {"id":"calibration-yellow-state","name":"Yellow-state cell on change","description":"After any rating change, the cell shows original (strikethrough) + new value side-by-side. Recency visible at a glance.","primary_user":"manager","surface":"calibration","help_mode":"manager-does-job","ai_mode":"none","inspiration":["15Five Talent Matrix"],"complexity":"S","poc_fit":True,"trust_pattern":"Original always visible until calibration locks. No silent overwrites."},
    {"id":"calibration-comment-on-move","name":"Comment-on-move thread","description":"Each rating change spawns a threaded dialogue bubble with the justification. @mentions and activity feed bound to the move.","primary_user":"manager","surface":"calibration","help_mode":"manager-does-job","ai_mode":"none","inspiration":["15Five threaded calibration","Workday Activity Stream"],"complexity":"M","poc_fit":True,"trust_pattern":"Comments are tied to moves, not buried in chat. Audit-ready."},
    {"id":"calibration-multi-cycle-history","name":"Multi-cycle history inline","description":"3 prior cycles shown in each row of the calibration table. Recency bias visible without context-switching.","primary_user":"manager","surface":"calibration","help_mode":"manager-does-job","ai_mode":"retrieve","inspiration":["Culture Amp"],"complexity":"S","poc_fit":True,"trust_pattern":"History is data, not narrative. Manager interprets."},
    {"id":"calibration-rater-distribution","name":"Per-rater distribution panel","description":"For each manager: their rating distribution vs the all-managers mean. Names the *manager pattern*, never any employee.","primary_user":"hr","surface":"calibration","help_mode":"hr-sees-patterns","ai_mode":"aggregate","inspiration":["Greenhouse Interviewer Calibration"],"complexity":"M","poc_fit":True,"trust_pattern":"Pattern-level surface. Confidence interval visible for small samples."},
    {"id":"calibration-permission-tiers","name":"Calibration permission tiers","description":"HR sees demographics; contributors see custom attributes only; participants never see calibration history.","primary_user":"hr","surface":"calibration","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Lattice scoped views"],"complexity":"M","poc_fit":True,"trust_pattern":"Permissions are visible to viewers. 'Redacted' rather than 'missing.'"},
    {"id":"calibration-activity-feed","name":"Calibration activity feed","description":"All changes auto-logged with user attribution. Export as audit log for the cycle.","primary_user":"hr","surface":"calibration","help_mode":"hr-sees-patterns","ai_mode":"none","inspiration":["Workday","Confirm"],"complexity":"M","poc_fit":True,"trust_pattern":"Immutable. Required evidence for burden-of-proof reversal."},
    {"id":"calibration-evidence-drawer","name":"Per-employee evidence drawer","description":"Click a name in calibration → full review history, peer feedback, prior comments, AI summary with sources. Calibrators read; never relabel.","primary_user":"manager","surface":"calibration","help_mode":"manager-does-job","ai_mode":"retrieve","inspiration":["Confirm","Lattice"],"complexity":"M","poc_fit":True,"trust_pattern":"Read-only. All sources cited."},
    {"id":"calibration-column-manager","name":"Calibration column manager","description":"Show/hide/reorder columns in the calibration table. Preferences persisted per user.","primary_user":"manager","surface":"calibration","help_mode":"manager-does-job","ai_mode":"none","inspiration":["15Five","Confirm"],"complexity":"S","poc_fit":True,"trust_pattern":"Personal layout, no impact on others."},
    {"id":"calibration-async-preview","name":"Async pre-meeting Ratings Preview","description":"Calibrators react to manager ratings before the live session. Deltas surface as the meeting's agenda.","primary_user":"manager","surface":"calibration","help_mode":"manager-does-job","ai_mode":"none","inspiration":["Culture Amp Ratings Preview"],"complexity":"M","poc_fit":False,"trust_pattern":"Async input visible to managers before the meeting. Saves meeting time, surfaces disagreement early."},
    {"id":"calibration-lock-realignment","name":"Lock with comment-realignment prompt","description":"When locking, prompt managers to update their written feedback to match the calibrated rating before sharing with employees.","primary_user":"manager","surface":"calibration","help_mode":"manager-does-job","ai_mode":"none","inspiration":["Confirm"],"complexity":"M","poc_fit":False,"trust_pattern":"Forces consistency between written feedback and final rating. Manager owns the edit."},
    {"id":"calibration-facilitator-prompts","name":"Facilitator intervention prompts","description":"When a flagged move surfaces, the facilitator gets scripted prompts ('Walk us through one example from Q1') — never auto-decides.","primary_user":"hr","surface":"calibration","help_mode":"hr-sees-patterns","ai_mode":"retrieve","inspiration":["HR facilitation best practices"],"complexity":"M","poc_fit":False,"trust_pattern":"Scripts authored by HR. LLM only adapts to the report's context, not the verdict."},
]

# Additional rejected items (consolidating researcher anti-pattern lists)
NEW_REJECTED = [
    {"name":"Real-time AI prompts during a 1:1","found_in":["Outreach Kaia"],"reason":"Manager becomes a puppet. Report can feel something is 'off.' Erodes trust at the highest-frequency manager touchpoint."},
    {"name":"Auto-detected 'winning behaviors' on individuals","found_in":["Gong","Chorus"],"reason":"Treats people as patterns to optimize. Crosses into behavioral surveillance."},
    {"name":"Personality scoring from public data","found_in":["Crystal"],"reason":"DISC/MBTI on people without consent. CNIL / GDPR red flag in EU. Drift toward judgment."},
    {"name":"Public leaderboard of writing scores","found_in":["Lavender consumer mode"],"reason":"Public ranking of employees on writing quality is degrading and chills honesty."},
    {"name":"\"Deal health\" red/yellow/green per individual","found_in":["Gong"],"reason":"Treats colour as truth. Invites manager laziness — the dashboard makes the call."},
    {"name":"Calendar hard-block auto-bookings","found_in":["Reclaim aggressive mode","Motion"],"reason":"Loss of autonomy. Prescription where description was needed. Calendar proposals must be opt-in."},
    {"name":"Auto-recording every 1:1 by default","found_in":["Spinach","Fellow"],"reason":"Freezes candor. Recording must be explicit, opt-in, per session. Most EU works councils would refuse the default."},
    {"name":"Agent autonomously acts on tickets","found_in":["Linear AI / Codex","Asana AI Teammates"],"reason":"Translated to perf: AI auto-writing review text and submitting. Removes the human signature; legally fraught (FR requires manager-signed appraisals)."},
    {"name":"Cross-employee retrieval (\"show me everyone who…\")","found_in":["Glean misconfigured","Workday Insights"],"reason":"Becomes ranking infrastructure. Permissioned RAG is fine; cross-employee retrieval is not."},
    {"name":"Coaching transcripts shared with manager","found_in":["Bravely mis-port"],"reason":"Confidentiality is the product. Breaking it kills the value."},
    {"name":"Talk-time ratio metrics on 1:1s","found_in":["Gong-style"],"reason":"Quantifies the wrong thing as proxy for quality. Classic Goodhart."},
    {"name":"Mandatory specificity that blocks submission","found_in":["aggressive Effy modes"],"reason":"Turns 'help' into 'obstruction.' Specificity coaches must always have an escape."},
    {"name":"AI bias auto-redaction without showing the change","found_in":["Macorva aggressive mode"],"reason":"Robs the reviewer of the learning moment. Suggest, don't silently write."},
    {"name":"AI-summarized 1:1 transcripts kept by default","found_in":["Spinach","Fellow"],"reason":"1:1 is between two people. Recording + summarizing changes the trust dynamic. Manager logs their own typed notes; system never listens."},
    {"name":"\"Signed by AI\" review artifacts","found_in":["various draft-and-sign demos"],"reason":"EU AI Act high-risk obligations require named human accountability. AI can draft; only a human signs."},
]

# --- Load seed ---
with SEED.open() as f:
    data = json.load(f)

# Build set of existing IDs to avoid duplicates
existing = {f["id"] for f in data["features"]}
existing_rejected_names = {r["name"].lower() for r in data["rejected"]}

added = 0
for f in NEW_FEATURES:
    if f["id"] in existing:
        continue
    data["features"].append(f)
    existing.add(f["id"])
    added += 1

added_rejected = 0
for r in NEW_REJECTED:
    if r["name"].lower() in existing_rejected_names:
        continue
    data["rejected"].append(r)
    existing_rejected_names.add(r["name"].lower())
    added_rejected += 1

# --- Write back features.json ---
with SEED.open("w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

# --- Build self-contained HTML by inlining the data ---
html_text = HTML_IN.read_text()

# Replace the fetch block with an inline assignment
fetch_block_re = re.compile(
    r"// Load features when script populates window\.FEATURES.*?$\s*}\);",
    re.DOTALL | re.MULTILINE,
)
inline_data = (
    "window.FEATURES = "
    + json.dumps(data["features"], ensure_ascii=False)
    + ";\n"
    + "window.REJECTED = "
    + json.dumps(data["rejected"], ensure_ascii=False)
    + ";\n"
    + "document.getElementById('loading-banner').style.display = 'none';\n"
    + "render();\nrenderRejected();"
)

if fetch_block_re.search(html_text):
    html_text = fetch_block_re.sub(inline_data, html_text)
else:
    # Idempotent: replace any prior inline assignment
    inline_re = re.compile(
        r"window\.FEATURES = .*?renderRejected\(\);", re.DOTALL
    )
    html_text = inline_re.sub(inline_data, html_text)

HTML_OUT.write_text(html_text)

print(f"Added {added} new features, {added_rejected} new rejected items.")
print(f"Total features: {len(data['features'])}, rejected: {len(data['rejected'])}.")
print(f"HTML written to {HTML_OUT}")
